import { type FormEvent, type ReactNode, useState } from 'react'
import { X } from 'lucide-react'
import { createVendor, type ApiStatus, type VendorCreateInput } from './api'
import { Button, IconButton } from './components'
import type { Vendor } from './types'

type FormErrors = Partial<Record<keyof VendorCreateInput, string>>
const initialForm: VendorCreateInput = { name:'', business_type:'', owner_name:'', phone:'', email:'', address:'', status:'pending' }

export function AddVendor({onClose,onCreated}:{onClose:()=>void;onCreated:(vendor:Vendor)=>void}){
 const [form,setForm]=useState<VendorCreateInput>(initialForm);const [errors,setErrors]=useState<FormErrors>({});const [apiError,setApiError]=useState('');const [submitting,setSubmitting]=useState(false)
 const update=(field:keyof VendorCreateInput,value:string)=>{setForm(current=>({...current,[field]:value}));setErrors(current=>({...current,[field]:undefined}));setApiError('')}
 const validate=()=>{const next:FormErrors={};(['name','business_type','owner_name','phone','email','address'] as const).forEach(field=>{if(!form[field].trim())next[field]='This field is required.'});if(form.email&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email='Enter a valid email address.';setErrors(next);return !Object.keys(next).length}
 const submit=async(event:FormEvent)=>{event.preventDefault();if(submitting||!validate())return;setSubmitting(true);setApiError('');try{const vendor=await createVendor(form);onCreated(vendor)}catch{setApiError('Unable to create this vendor. Check the information and try again.')}finally{setSubmitting(false)}}
 return <div className="details-backdrop" role="presentation" onMouseDown={onClose}><aside className="details-panel add-vendor-panel" role="dialog" aria-modal="true" aria-labelledby="add-vendor-title" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">Vendor management</p><h2 id="add-vendor-title">Add vendor</h2></div><IconButton label="Close add vendor form" onClick={onClose} disabled={submitting}><X size={18}/></IconButton></header><form className="vendor-form" onSubmit={submit} noValidate>{apiError&&<div className="api-error">{apiError}</div>}<Field label="Vendor name" error={errors.name}><input value={form.name} onChange={e=>update('name',e.target.value)} autoFocus/></Field><Field label="Business type" error={errors.business_type}><input value={form.business_type} onChange={e=>update('business_type',e.target.value)} placeholder="e.g. Clothing"/></Field><Field label="Owner name" error={errors.owner_name}><input value={form.owner_name} onChange={e=>update('owner_name',e.target.value)}/></Field><Field label="Phone" error={errors.phone}><input value={form.phone} onChange={e=>update('phone',e.target.value)} type="tel"/></Field><Field label="Email" error={errors.email}><input value={form.email} onChange={e=>update('email',e.target.value)} type="email"/></Field><Field label="Address" error={errors.address}><textarea value={form.address} onChange={e=>update('address',e.target.value)} rows={3}/></Field><Field label="Status"><select value={form.status} onChange={e=>update('status',e.target.value as ApiStatus)}><option value="pending">Pending</option><option value="active">Active</option><option value="inactive">Inactive</option></select></Field><footer><Button type="button" onClick={onClose} disabled={submitting}>Cancel</Button><Button variant="primary" type="submit" loading={submitting}>Create vendor</Button></footer></form></aside></div>
}
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="form-field"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
