import { useEffect, useState } from 'react'
import { Download, Filter, Grid2X2, List, SlidersHorizontal, TrendingUp } from 'lucide-react'
import { Avatar, Badge, Button, Card, DataTable, DonutChart, IconButton, Pagination, SearchField, Tabs, Toast } from './components'
import { Sidebar, Topbar } from './layout'
import type { Column, Vendor } from './types'
import { getVendorDashboard, getVendors, toVendor, type VendorDashboard } from './api'
import { VendorDetails } from './VendorDetails'

const columns: Column<Vendor>[]=[
 {key:'vendor',label:'Vendor',render:v=><strong className="vendor-name"><span className="vendor-logo">⌁</span>{v.name}</strong>}, {key:'type',label:'Business type',render:v=>v.category},
 {key:'owner',label:'Owner',render:v=><span className="owner"><Avatar initials={v.initials} small/>{v.owner}</span>}, {key:'phone',label:'Number',render:v=>v.phone}, {key:'email',label:'Email',render:v=>v.email}, {key:'orders',label:'Order',render:v=>v.orders}, {key:'address',label:'Address',render:v=>v.address}, {key:'status',label:'Status',render:v=><Badge status={v.status}/>}
]
function Dashboard({search}:{search:string}){ const [tab,setTab]=useState('All');const [page,setPage]=useState(1);const [toast,setToast]=useState('');const [tableQuery,setTableQuery]=useState('');const [rows,setRows]=useState<Vendor[]>([]);const [total,setTotal]=useState(0);const [summary,setSummary]=useState<VendorDashboard|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [detailsId,setDetailsId]=useState<string|null>(null);const query=search||tableQuery;
 useEffect(()=>{setPage(1)},[tab,query]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.all([getVendors({page,query,status:tab,signal:controller.signal}),getVendorDashboard(controller.signal)]).then(([vendorPage,dashboard])=>{setRows(vendorPage.results);setTotal(vendorPage.count);setSummary(dashboard)}).catch(err=>{if(err.name!=='AbortError')setError('Could not reach the logistics API. Start Django on port 8000, then refresh.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[page,query,tab]);
 const pending=(summary?.pending ?? []).map(toVendor);const action=(name:string,vendor:Vendor)=>name==='View details'?setDetailsId(vendor.id):setToast(`${name}: ${vendor.name}`);return <main className="content"><div className="summary-grid"><Card className="metric-card"><div className="card-header"><h2>Vendors</h2><Button>Live API data</Button></div><div className="metric-body"><div><span className="eyebrow">Total Vendors</span><strong className="big-number">{summary?.total_vendors ?? '—'}</strong><p className="positive"><TrendingUp size={13}/> Live <i>from Django REST API</i></p></div><DonutChart/></div><div className="legend"><span><i className="active-dot"/>Active <b>{summary?.active_vendors ?? '—'}</b></span><span><i className="inactive-dot"/>Inactive <b>{summary?.inactive_vendors ?? '—'}</b></span><span><i className="pending-dot"/>Pending <b>{summary?.pending_vendors ?? '—'}</b></span></div></Card><Card className="pending-card"><div className="card-header"><div><h2>Pending Vendors</h2><p>Live vendor records awaiting verification.</p></div></div><div className="pending-list">{pending.slice(0,2).map(v=><article className="pending-item" key={v.id}><Avatar initials={v.initials}/><div><strong>{v.name}</strong><p>{v.address}</p><Button onClick={()=>setDetailsId(v.id)}>View Details</Button></div><Badge status="Pending"/></article>)}{!loading&&!pending.length&&<p className="empty-state">No pending vendors.</p>}</div></Card></div><Card className="table-card"><div className="table-top"><h2>Vendors</h2><div className="table-actions"><Button><Filter size={14}/> Filters</Button><Button><SlidersHorizontal size={14}/> Manage</Button><Button><Download size={14}/> Export</Button><IconButton label="List view"><List size={16}/></IconButton><IconButton label="Grid view"><Grid2X2 size={16}/></IconButton></div></div><div className="table-tools"><Tabs tabs={['All','Active','Inactive','Pending']} value={tab} onChange={setTab}/><SearchField value={tableQuery} onChange={setTableQuery}/></div>{error?<div className="api-error">{error}</div>:loading?<div className="api-loading">Loading vendor records…</div>:<><DataTable columns={columns} rows={rows} onAction={action}/><footer className="table-footer"><span>Showing {total ? (page-1)*6+1 : 0} to {Math.min(page*6,total)} of {total}</span><Pagination page={page} pages={Math.max(1,Math.ceil(total/6))} onChange={setPage}/></footer></>}</Card><VendorDetails vendorId={detailsId} onClose={()=>setDetailsId(null)}/>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</main>}
function Styleguide(){return <main className="content styleguide"><div className="page-title"><p className="eyebrow">Foundations & components</p><h1>Design system</h1><p>A compact admin interface designed for logistics operations.</p></div><Card><h2>Color tokens</h2><div className="swatches">{['--primary','--canvas','--surface','--text','--success','--danger','--warning'].map(t=><div key={t}><span style={{background:`var(${t})`}}/><code>{t.replace('--','')}</code></div>)}</div></Card><div className="style-grid"><Card><h2>Buttons</h2><div className="showcase"><Button variant="primary">Add new</Button><Button>Secondary</Button><Button variant="ghost">Ghost</Button><Button disabled>Disabled</Button></div></Card><Card><h2>Status</h2><div className="showcase"><Badge status="Active"/><Badge status="Inactive"/><Badge status="Pending"/></div></Card></div><Card><h2>Interface patterns</h2><div className="showcase"><SearchField value="" onChange={()=>{}}/><Tabs tabs={['All','Active','Pending']} value="All" onChange={()=>{}}/><Avatar initials="DV"/><IconButton label="Example control"><List size={16}/></IconButton></div></Card></main>}
export function App(){const [theme,setTheme]=useState(()=>localStorage.getItem('truelog-theme')||'light'); const [sidebar,setSidebar]=useState(false);const [styleguide,setStyleguide]=useState(location.hash==='#/styleguide');const [search,setSearch]=useState(''); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('truelog-theme',theme)},[theme]);const navigate=(s:boolean)=>{setStyleguide(s);location.hash=s?'/styleguide':'';setSidebar(false)};return <div className="app-shell"><Sidebar open={sidebar} onClose={()=>setSidebar(false)} styleguide={styleguide} onNavigate={navigate}/><div className="app-main"><Topbar onMenu={()=>setSidebar(true)} theme={theme} setTheme={()=>setTheme(theme==='light'?'dark':'light')} onSearch={setSearch} styleguide={styleguide} onNavigate={navigate}/>{styleguide?<Styleguide/>:<Dashboard search={search}/>}</div></div>}
