import { type FormEvent, useEffect, useState } from 'react'
import { Bike, MapPin, Phone, Star, X } from 'lucide-react'
import { ApiError, assignRider, getAvailableRiders } from './api'
import { Avatar, Button, IconButton } from './components'
import type { Order, Rider } from './types'

const errorMessage=(error:unknown)=>{if(!(error instanceof ApiError))return 'Unable to assign this rider. Check the API connection and try again.';const value=error.fields.rider||error.fields.non_field_errors||error.fields.detail;if(!value)return 'Unable to assign this rider. Please try again.';return Array.isArray(value)?value.join(' '):String(value)}
export function AssignRider({order,onClose,onAssigned}:{order:Order;onClose:()=>void;onAssigned:(order:Order)=>void}){
 const [riders,setRiders]=useState<Rider[]>([]);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true);const [assigning,setAssigning]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{const controller=new AbortController();getAvailableRiders(controller.signal).then(setRiders).catch(err=>{if(err.name!=='AbortError')setError('Unable to load available riders. Please try again.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[])
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!assigning)onClose()};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[assigning,onClose])
 const submit=async(event:FormEvent)=>{event.preventDefault();if(assigning||!selected)return;setAssigning(true);setError('');try{onAssigned(await assignRider(order.id,selected))}catch(err){setError(errorMessage(err))}finally{setAssigning(false)}}
 return <div className="details-backdrop" role="presentation" onMouseDown={()=>!assigning&&onClose()}><aside className="details-panel assignment-panel" role="dialog" aria-modal="true" aria-labelledby="assign-rider-title" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">Delivery operations</p><h2 id="assign-rider-title">Assign rider</h2></div><IconButton label="Close rider assignment" onClick={onClose} disabled={assigning}><X size={18}/></IconButton></header><form onSubmit={submit}><div className="assignment-order"><strong>{order.reference}</strong><span><MapPin/> {order.pickupAddress}</span><span><MapPin/> {order.deliveryAddress}</span></div><div className="assignment-list"><h3>Available Riders</h3>{error&&<div className="api-error" role="alert">{error}</div>}{loading?<div className="details-loading">Loading available riders…</div>:riders.length===0?<p className="assignment-empty">No riders are currently available.</p>:riders.map(rider=><label className={`rider-option ${selected===rider.id?'selected':''}`} key={rider.id}><input type="radio" name="rider" value={rider.id} checked={selected===rider.id} onChange={()=>{setSelected(rider.id);setError('')}}/><Avatar initials={rider.initials}/><span><strong>{rider.name}</strong><small><Phone/> {rider.phone}</small><small><Star/> Rating: {rider.rating} · Active orders: {rider.activeOrders}</small></span></label>)}</div><footer><Button type="button" onClick={onClose} disabled={assigning}>Cancel</Button><Button variant="primary" type="submit" disabled={!selected||loading||riders.length===0||assigning}>{assigning?'Assigning...':<><Bike size={14}/>Assign Rider</>}</Button></footer></form></aside></div>
}
