import { forwardRef, type ButtonHTMLAttributes, type ReactNode, useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Check, CheckCircle2, ChevronDown, MoreVertical, Pencil, Search, Trash2, X } from 'lucide-react'
import type { Column, Status } from './types'

export function Button({ variant='secondary', loading, children, className='', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & {variant?:'primary'|'secondary'|'ghost';loading?:boolean}) { return <button className={`button ${variant} ${className}`} disabled={loading || props.disabled} {...props}>{loading ? 'Loading…' : children}</button> }
export const IconButton = forwardRef<HTMLButtonElement, ButtonHTMLAttributes<HTMLButtonElement> & {label:string}>(({label, children, className='', ...props}, ref) => <button ref={ref} className={`icon-button ${className}`} aria-label={label} title={label} {...props}>{children}</button>)
export function SearchField({value, onChange, placeholder='Search…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}) { return <label className="search-field"><Search size={14}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value && <button aria-label="Clear search" onClick={()=>onChange('')}><X size={13}/></button>}</label> }
export function Select({children, ...props}: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className="select" {...props}>{children}</select> }
export function Badge({status}:{status:Status}) { return <span className={`badge ${status.toLowerCase()}`}>{status}</span> }
export function Avatar({initials, small=false}:{initials:string;small?:boolean}) { return <span className={`avatar ${small?'small':''}`}>{initials}</span> }
export function Checkbox({checked, onChange}:{checked?:boolean;onChange?:()=>void}) { return <button role="checkbox" aria-checked={checked} onClick={onChange} className={`checkbox ${checked?'checked':''}`}>{checked && <Check size={12}/>}</button> }
export function Tabs({tabs, value, onChange}:{tabs:string[];value:string;onChange:(t:string)=>void}) { return <div className="tabs" role="tablist">{tabs.map(tab=><button key={tab} role="tab" aria-selected={value===tab} className={value===tab?'selected':''} onClick={()=>onChange(tab)}>{tab}</button>)}</div> }
export function Card({children, className=''}:{children:ReactNode;className?:string}) { return <section className={`card ${className}`}>{children}</section> }
export const vendorStatusAction = (status:Status) => status === 'Pending' ? {label:'Approve vendor', next:'active' as const} : status === 'Active' ? {label:'Deactivate vendor', next:'inactive' as const} : {label:'Activate vendor', next:'active' as const}
export function DropdownMenu<T extends {status:Status}>({row,onAction,loading=false}:{row:T;onAction:(action:'details'|'edit'|'status'|'delete',row:T)=>void;loading?:boolean}) { const [open,setOpen]=useState(false); const triggerRef=useRef<HTMLButtonElement>(null); const menuRef=useRef<HTMLDivElement>(null); const [position,setPosition]=useState({top:0,left:0,up:false}); const statusAction=vendorStatusAction(row.status);const toggle=()=>{if(open){setOpen(false);return}const rect=triggerRef.current!.getBoundingClientRect();const menuHeight=164;const up=window.innerHeight-rect.bottom<menuHeight+12;setPosition({top:up?rect.top:rect.bottom,left:Math.max(8,rect.right-176),up});setOpen(true)};useEffect(()=>{const close=(e:MouseEvent)=>{const target=e.target as Node;if(!triggerRef.current?.contains(target)&&!menuRef.current?.contains(target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('scroll',close,true);window.addEventListener('resize',close);return()=>{window.removeEventListener('scroll',close,true);window.removeEventListener('resize',close)}},[]);const choose=(action:'details'|'edit'|'status'|'delete')=>{onAction(action,row);setOpen(false)}; return <div className="menu"><IconButton label="Vendor actions" onClick={toggle} disabled={loading} ref={triggerRef}><MoreVertical size={16}/></IconButton>{open&&createPortal(<div ref={menuRef} className={`menu-popover ${position.up?'opens-up':''}`} style={{top:position.top,left:position.left}} role="menu" aria-label="Vendor actions"><button role="menuitem" onClick={()=>choose('details')} disabled={loading}><Search size={14}/>View details</button><button role="menuitem" onClick={()=>choose('edit')} disabled={loading}><Pencil size={14}/>Edit vendor</button><button role="menuitem" onClick={()=>choose('status')} disabled={loading}><CheckCircle2 size={14}/>{loading?'Updating…':statusAction.label}</button><button className="danger-menu-item" role="menuitem" onClick={()=>choose('delete')} disabled={loading}><Trash2 size={14}/>Delete vendor</button></div>,document.body)}</div> }
export function ViewDetailsMenu({label,onDetails,actions=[],loading=false}:{label:string;onDetails:()=>void;actions?:{label:string;onClick:()=>void;danger?:boolean}[];loading?:boolean}){const [open,setOpen]=useState(false);const triggerRef=useRef<HTMLButtonElement>(null);const menuRef=useRef<HTMLDivElement>(null);const [position,setPosition]=useState({top:0,left:0,up:false});const toggle=(event:React.MouseEvent)=>{event.stopPropagation();if(open){setOpen(false);return}const rect=triggerRef.current!.getBoundingClientRect();const menuHeight=(actions.length+1)*38+10;const up=window.innerHeight-rect.bottom<menuHeight+12;setPosition({top:up?rect.top:rect.bottom,left:Math.max(8,rect.right-176),up});setOpen(true)};useEffect(()=>{const close=(event:MouseEvent)=>{const target=event.target as Node;if(!triggerRef.current?.contains(target)&&!menuRef.current?.contains(target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('scroll',close,true);window.addEventListener('resize',close);return()=>{window.removeEventListener('scroll',close,true);window.removeEventListener('resize',close)}},[]);const choose=(event:React.MouseEvent,action:()=>void)=>{event.stopPropagation();setOpen(false);action()};return <div className="menu"><IconButton ref={triggerRef} label={label} aria-expanded={open} aria-haspopup="menu" onClick={toggle} disabled={loading}><MoreVertical size={16}/></IconButton>{open&&createPortal(<div ref={menuRef} className={`menu-popover ${position.up?'opens-up':''}`} style={{top:position.top,left:position.left}} role="menu" aria-label={label}><button role="menuitem" onClick={event=>choose(event,onDetails)} disabled={loading}><Search size={14}/>View details</button>{actions.map(action=><button key={action.label} className={action.danger?'danger-menu-item':undefined} role="menuitem" onClick={event=>choose(event,action.onClick)} disabled={loading}>{action.label}</button>)}</div>,document.body)}</div>}
export function CrudMenu({label,entity,onView,onEdit,onDelete}:{label:string;entity:string;onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);const triggerRef=useRef<HTMLButtonElement>(null);const menuRef=useRef<HTMLDivElement>(null);const [position,setPosition]=useState({top:0,left:0,up:false});const toggle=()=>{if(open){setOpen(false);return}const rect=triggerRef.current!.getBoundingClientRect();const up=window.innerHeight-rect.bottom<125;setPosition({top:up?rect.top:rect.bottom,left:Math.max(8,rect.right-176),up});setOpen(true)};useEffect(()=>{const close=(event:MouseEvent)=>{const target=event.target as Node;if(!triggerRef.current?.contains(target)&&!menuRef.current?.contains(target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('scroll',close,true);window.addEventListener('resize',close);return()=>{window.removeEventListener('scroll',close,true);window.removeEventListener('resize',close)}},[]);const choose=(action:()=>void)=>{setOpen(false);action()};return <div className="menu"><IconButton ref={triggerRef} label={label} onClick={toggle}><MoreVertical size={16}/></IconButton>{open&&createPortal(<div ref={menuRef} className={`menu-popover ${position.up?'opens-up':''}`} style={{top:position.top,left:position.left}} role="menu" aria-label={label}><button role="menuitem" onClick={()=>choose(onView)}><Search size={14}/>View details</button><button role="menuitem" onClick={()=>choose(onEdit)}><Pencil size={14}/>Edit {entity}</button><button className="danger-menu-item" role="menuitem" onClick={()=>choose(onDelete)}><Trash2 size={14}/>Delete {entity}</button></div>,document.body)}</div>}
export function Pagination({page, pages, onChange}:{page:number;pages:number;onChange:(page:number)=>void}) { return <nav className="pagination" aria-label="Pagination"><Button onClick={()=>onChange(Math.max(1,page-1))} aria-label="Previous page">‹</Button>{Array.from({length:pages},(_,i)=>i+1).map(p=><button key={p} className={p===page?'current':''} onClick={()=>onChange(p)}>{p}</button>)}<Button onClick={()=>onChange(Math.min(pages,page+1))} aria-label="Next page">›</Button></nav> }
export function DataTable<T extends {id:string|number;status:Status}>({columns, rows, onAction, updatingId}:{columns:Column<T>[];rows:T[];onAction:(action:'details'|'edit'|'status'|'delete',row:T)=>void;updatingId?:string|number|null}) { const [all,setAll]=useState(false);return <div className="table-wrap"><table><thead><tr><th><Checkbox checked={all} onChange={()=>setAll(!all)}/></th>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Checkbox checked={all}/></td>{columns.map(c=><td className={c.className} key={c.key}>{c.render(row)}</td>)}<td><DropdownMenu row={row} onAction={onAction} loading={updatingId===row.id}/></td></tr>)}</tbody></table></div> }
export function DonutChart(){return <div className="donut" aria-label="Vendor status distribution"><div><strong>10.5K</strong><small>vendors</small></div></div>}
export function Toast({message,onClose}:{message:string;onClose:()=>void}){return <div className="toast" role="status">{message}<button aria-label="Dismiss" onClick={onClose}>×</button></div>}
