import { type ButtonHTMLAttributes, type ReactNode, useEffect, useRef, useState } from 'react'
import { Check, ChevronDown, MoreVertical, Search, X } from 'lucide-react'
import type { Column, Status } from './types'

export function Button({ variant='secondary', loading, children, className='', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & {variant?:'primary'|'secondary'|'ghost';loading?:boolean}) { return <button className={`button ${variant} ${className}`} disabled={loading || props.disabled} {...props}>{loading ? 'Loading…' : children}</button> }
export function IconButton({label, children, className='', ...props}: ButtonHTMLAttributes<HTMLButtonElement> & {label:string}) { return <button className={`icon-button ${className}`} aria-label={label} title={label} {...props}>{children}</button> }
export function SearchField({value, onChange, placeholder='Search…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}) { return <label className="search-field"><Search size={14}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value && <button aria-label="Clear search" onClick={()=>onChange('')}><X size={13}/></button>}</label> }
export function Select({children, ...props}: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className="select" {...props}>{children}</select> }
export function Badge({status}:{status:Status}) { return <span className={`badge ${status.toLowerCase()}`}>{status}</span> }
export function Avatar({initials, small=false}:{initials:string;small?:boolean}) { return <span className={`avatar ${small?'small':''}`}>{initials}</span> }
export function Checkbox({checked, onChange}:{checked?:boolean;onChange?:()=>void}) { return <button role="checkbox" aria-checked={checked} onClick={onChange} className={`checkbox ${checked?'checked':''}`}>{checked && <Check size={12}/>}</button> }
export function Tabs({tabs, value, onChange}:{tabs:string[];value:string;onChange:(t:string)=>void}) { return <div className="tabs" role="tablist">{tabs.map(tab=><button key={tab} role="tab" aria-selected={value===tab} className={value===tab?'selected':''} onClick={()=>onChange(tab)}>{tab}</button>)}</div> }
export function Card({children, className=''}:{children:ReactNode;className?:string}) { return <section className={`card ${className}`}>{children}</section> }
export const vendorStatusAction = (status:Status) => status === 'Pending' ? {label:'Approve vendor', next:'active' as const} : status === 'Active' ? {label:'Deactivate vendor', next:'inactive' as const} : {label:'Activate vendor', next:'active' as const}
export function DropdownMenu<T extends {status:Status}>({row,onAction,loading=false}:{row:T;onAction:(action:'details'|'status',row:T)=>void;loading?:boolean}) { const [open,setOpen]=useState(false); const ref=useRef<HTMLDivElement>(null); const statusAction=vendorStatusAction(row.status);useEffect(()=>{ const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]); return <div className="menu" ref={ref}><IconButton label="Vendor actions" onClick={()=>setOpen(!open)} disabled={loading}><MoreVertical size={16}/></IconButton>{open&&<div className="menu-popover"><button onClick={()=>{onAction('details',row);setOpen(false)}} disabled={loading}>View details</button><button onClick={()=>{onAction('status',row);setOpen(false)}} disabled={loading}>{loading?'Updating…':statusAction.label}</button></div>}</div> }
export function Pagination({page, pages, onChange}:{page:number;pages:number;onChange:(page:number)=>void}) { return <nav className="pagination" aria-label="Pagination"><Button onClick={()=>onChange(Math.max(1,page-1))} aria-label="Previous page">‹</Button>{Array.from({length:pages},(_,i)=>i+1).map(p=><button key={p} className={p===page?'current':''} onClick={()=>onChange(p)}>{p}</button>)}<Button onClick={()=>onChange(Math.min(pages,page+1))} aria-label="Next page">›</Button></nav> }
export function DataTable<T extends {id:string|number;status:Status}>({columns, rows, onAction, updatingId}:{columns:Column<T>[];rows:T[];onAction:(action:'details'|'status',row:T)=>void;updatingId?:string|number|null}) { const [all,setAll]=useState(false);return <div className="table-wrap"><table><thead><tr><th><Checkbox checked={all} onChange={()=>setAll(!all)}/></th>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Checkbox checked={all}/></td>{columns.map(c=><td className={c.className} key={c.key}>{c.render(row)}</td>)}<td><DropdownMenu row={row} onAction={onAction} loading={updatingId===row.id}/></td></tr>)}</tbody></table></div> }
export function DonutChart(){return <div className="donut" aria-label="Vendor status distribution"><div><strong>10.5K</strong><small>vendors</small></div></div>}
export function Toast({message,onClose}:{message:string;onClose:()=>void}){return <div className="toast" role="status">{message}<button aria-label="Dismiss" onClick={onClose}>×</button></div>}
