import { type FormEvent, type ReactNode, useEffect, useState } from 'react'
import { X } from 'lucide-react'
import { ApiError, createOrder, getOrderFormOptions, type ApiOrderStatus, type OrderCreateInput } from './api'
import { Button, IconButton } from './components'
import type { Order } from './types'

type Field=keyof OrderCreateInput
type FormErrors=Partial<Record<Field,string>>
const initialForm:OrderCreateInput={reference:'',vendor:'',rider:null,pickup_address:'',delivery_address:'',recipient_name:'',recipient_phone:'',status:'pending',delivery_fee:''}
const statuses:{value:ApiOrderStatus;label:string}[]=[{value:'pending',label:'Pending'},{value:'assigned',label:'Assigned'},{value:'picked_up',label:'Picked up'},{value:'delivered',label:'Delivered'},{value:'cancelled',label:'Cancelled'}]

export function CreateOrder({onClose,onCreated}:{onClose:()=>void;onCreated:(order:Order)=>void}){const [form,setForm]=useState<OrderCreateInput>(initialForm);const [errors,setErrors]=useState<FormErrors>({});const [apiError,setApiError]=useState('');const [submitting,setSubmitting]=useState(false);const [optionsLoading,setOptionsLoading]=useState(true);const [vendors,setVendors]=useState<{id:string;name:string}[]>([]);const [riders,setRiders]=useState<{id:string;full_name:string;status:string}[]>([])
 useEffect(()=>{const controller=new AbortController();getOrderFormOptions(controller.signal).then(data=>{setVendors(data.vendors.map(({id,name})=>({id,name})));setRiders(data.riders.map(({id,full_name,status})=>({id,full_name,status})))}).catch(error=>{if(error.name!=='AbortError')setApiError('Unable to load vendors and riders. Check the API connection and try again.')}).finally(()=>{if(!controller.signal.aborted)setOptionsLoading(false)});return()=>controller.abort()},[])
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!submitting)onClose()};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[onClose,submitting])
 const update=(field:Field,value:string|null)=>{setForm(current=>({...current,[field]:value}));setErrors(current=>({...current,[field]:undefined}));setApiError('')}
 const validate=()=>{const next:FormErrors={};(['reference','vendor','pickup_address','delivery_address','recipient_name','recipient_phone','delivery_fee'] as const).forEach(field=>{if(!String(form[field]??'').trim())next[field]='This field is required.'});if(form.reference.length>40)next.reference='Reference must be 40 characters or fewer.';if(form.recipient_phone&&!/^\+?[0-9 ()-]{7,32}$/.test(form.recipient_phone))next.recipient_phone='Enter a valid phone number.';const fee=Number(form.delivery_fee);if(form.delivery_fee&&(Number.isNaN(fee)||fee<0))next.delivery_fee='Enter a valid fee of zero or more.';if((form.status==='assigned'||form.status==='picked_up')&&!form.rider)next.rider='Select a rider for this status.';setErrors(next);return !Object.keys(next).length}
 const submit=async(event:FormEvent)=>{event.preventDefault();if(submitting||!validate())return;setSubmitting(true);setApiError('');try{onCreated(await createOrder(form))}catch(error){if(error instanceof ApiError){const fieldErrors:FormErrors={};Object.entries(error.fields).forEach(([field,messages])=>{if(field in initialForm)fieldErrors[field as Field]=Array.isArray(messages)?messages.join(' '):String(messages)});setErrors(current=>({...current,...fieldErrors}));const general=error.fields.non_field_errors||error.fields.detail;if(general)setApiError(Array.isArray(general)?general.join(' '):String(general));else if(!Object.keys(fieldErrors).length)setApiError('Unable to create this order. Check the information and try again.')}else setApiError('Unable to create this order. Check the API connection and try again.')}finally{setSubmitting(false)}}
 return <div className="details-backdrop" role="presentation" onMouseDown={()=>!submitting&&onClose()}><aside className="details-panel add-order-panel" role="dialog" aria-modal="true" aria-labelledby="create-order-title" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">Delivery operations</p><h2 id="create-order-title">Create order</h2></div><IconButton label="Close create order form" onClick={onClose} disabled={submitting}><X size={18}/></IconButton></header><form className="vendor-form" onSubmit={submit} noValidate>{apiError&&<div className="api-error">{apiError}</div>}<Field label="Order reference" error={errors.reference}><input value={form.reference} onChange={e=>update('reference',e.target.value)} maxLength={40} autoFocus/></Field><Field label="Vendor" error={errors.vendor}><select value={form.vendor} onChange={e=>update('vendor',e.target.value)} disabled={optionsLoading}><option value="">{optionsLoading?'Loading vendors…':'Select a vendor'}</option>{vendors.map(vendor=><option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select></Field><Field label="Recipient name" error={errors.recipient_name}><input value={form.recipient_name} onChange={e=>update('recipient_name',e.target.value)}/></Field><Field label="Recipient phone" error={errors.recipient_phone}><input type="tel" value={form.recipient_phone} onChange={e=>update('recipient_phone',e.target.value)}/></Field><Field label="Pickup location" error={errors.pickup_address}><textarea rows={2} value={form.pickup_address} onChange={e=>update('pickup_address',e.target.value)}/></Field><Field label="Delivery destination" error={errors.delivery_address}><textarea rows={2} value={form.delivery_address} onChange={e=>update('delivery_address',e.target.value)}/></Field><Field label="Delivery fee (NGN)" error={errors.delivery_fee}><input type="number" min="0" step="0.01" value={form.delivery_fee} onChange={e=>update('delivery_fee',e.target.value)}/></Field><Field label="Status" error={errors.status}><select value={form.status} onChange={e=>update('status',e.target.value as ApiOrderStatus)}>{statuses.map(status=><option key={status.value} value={status.value}>{status.label}</option>)}</select></Field><Field label="Assigned rider (optional)" error={errors.rider}><select value={form.rider??''} onChange={e=>update('rider',e.target.value||null)} disabled={optionsLoading}><option value="">Not assigned</option>{riders.map(rider=><option key={rider.id} value={rider.id} disabled={rider.status==='offline'}>{rider.full_name}{rider.status==='offline'?' (offline)':''}</option>)}</select></Field><footer><Button type="button" onClick={onClose} disabled={submitting}>Cancel</Button><Button variant="primary" type="submit" loading={submitting} disabled={optionsLoading}>Create order</Button></footer></form></aside></div>}
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="form-field"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
