import { useEffect, useState } from 'react'
import { PackageSearch, Plus } from 'lucide-react'
import { Badge, Button, Card, Pagination, SearchField, Tabs, Toast, ViewDetailsMenu } from './components'
import { getOrders, type ApiOrderStatus } from './api'
import { OrderDetails } from './OrderDetails'
import { CreateOrder } from './CreateOrder'
import type { Order } from './types'
import './orders.css'

const filters:{label:string;value:ApiOrderStatus|'all'}[]=[{label:'All',value:'all'},{label:'Pending',value:'pending'},{label:'Assigned',value:'assigned'},{label:'Picked up',value:'picked_up'},{label:'Delivered',value:'delivered'},{label:'Cancelled',value:'cancelled'}]
const money=(value:string)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2}).format(Number(value))
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value))

export function Orders({search}:{search:string}){const [filter,setFilter]=useState('All');const [tableQuery,setTableQuery]=useState('');const [page,setPage]=useState(1);const [orders,setOrders]=useState<Order[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [detailsId,setDetailsId]=useState<string|null>(null);const [createOpen,setCreateOpen]=useState(false);const [toast,setToast]=useState('');const [refreshVersion,setRefreshVersion]=useState(0);const query=search||tableQuery;const status=filters.find(item=>item.label===filter)?.value??'all'
 useEffect(()=>setPage(1),[query,filter])
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');getOrders({page,query,status,signal:controller.signal}).then(data=>{setOrders(data.results);setTotal(data.count)}).catch(err=>{if(err.name!=='AbortError')setError('Could not reach the logistics API. Start Django on port 8000, then refresh.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[page,query,status,refreshVersion])
 const created=(order:Order)=>{setCreateOpen(false);setPage(1);setFilter('All');setTableQuery('');setRefreshVersion(version=>version+1);setToast(`${order.reference} was created successfully.`)}
 return <main className="content orders-page"><div className="orders-page-header"><div className="page-title"><p className="eyebrow">Delivery operations</p><h1>Orders</h1><p>Track orders and inspect shipment details.</p></div><Button variant="primary" onClick={()=>setCreateOpen(true)}><Plus size={14}/>Add Order</Button></div><Card className="table-card orders-card"><div className="table-top"><div><h2>All orders</h2><p className="table-subtitle">{total} order{total===1?'':'s'} found</p></div></div><div className="table-tools"><Tabs tabs={filters.map(item=>item.label)} value={filter} onChange={setFilter}/><SearchField value={tableQuery} onChange={setTableQuery} placeholder="Search orders…"/></div>{error?<div className="api-error">{error}</div>:loading?<div className="api-loading">Loading order records…</div>:orders.length===0?<div className="orders-empty"><PackageSearch/><h3>No orders found</h3><p>{query||status!=='all'?'Try a different search or status filter.':'Orders will appear here when they are created.'}</p></div>:<><OrderTable orders={orders} onDetails={setDetailsId}/><footer className="table-footer"><span>Showing {total?(page-1)*6+1:0} to {Math.min(page*6,total)} of {total}</span><Pagination page={page} pages={Math.max(1,Math.ceil(total/6))} onChange={setPage}/></footer></>} </Card><OrderDetails orderId={detailsId} onClose={()=>setDetailsId(null)}/>{createOpen&&<CreateOrder onClose={()=>setCreateOpen(false)} onCreated={created}/>} {toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</main>}

function OrderTable({orders,onDetails}:{orders:Order[];onDetails:(id:string)=>void}){return <div className="table-wrap"><table className="orders-table"><thead><tr><th>Reference</th><th>Vendor</th><th>Recipient</th><th>Phone</th><th>Pickup location</th><th>Delivery destination</th><th>Delivery fee</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>{order.reference}</strong></td><td>{order.vendorName}</td><td>{order.recipientName}</td><td>{order.recipientPhone}</td><td className="address-cell" title={order.pickupAddress}>{order.pickupAddress}</td><td className="address-cell" title={order.deliveryAddress}>{order.deliveryAddress}</td><td>{money(order.deliveryFee)}</td><td><Badge status={order.status}/></td><td>{date(order.createdAt)}</td><td><ViewDetailsMenu label={`Actions for order ${order.reference}`} onDetails={()=>onDetails(order.id)}/></td></tr>)}</tbody></table></div>}
