import { type FormEvent, type ReactNode, useEffect, useState } from 'react'
import { X } from 'lucide-react'
import { ApiError, createRider, updateRider, type ApiRiderStatus, type RiderInput } from './api'
import { Button, IconButton } from './components'
import type { Rider } from './types'

type Errors=Partial<Record<keyof RiderInput,string>>
const empty:RiderInput={full_name:'',phone:'',email:'',status:'available',rating:'5.0'}
const toInput=(rider:Rider):RiderInput=>({full_name:rider.name,phone:rider.phone,email:rider.email,status:rider.status==='Available'?'available':rider.status==='On delivery'?'on_delivery':'offline',rating:rider.rating})
export function RiderForm({rider,onClose,onSaved}:{rider?:Rider;onClose:()=>void;onSaved:(rider:Rider)=>void}){const [form,setForm]=useState<RiderInput>(()=>rider?toInput(rider):empty);const [errors,setErrors]=useState<Errors>({});const [apiError,setApiError]=useState('');const [saving,setSaving]=useState(false);const edit=Boolean(rider)
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)onClose()};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[onClose,saving])
 const update=(field:keyof RiderInput,value:string)=>{setForm(current=>({...current,[field]:value}));setErrors(current=>({...current,[field]:undefined}));setApiError('')}
 const validate=()=>{const next:Errors={};(['full_name','phone','email','rating'] as const).forEach(field=>{if(!form[field].trim())next[field]='This field is required.'});if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email='Enter a valid email address.';if(form.phone&&!/^\+?[0-9 ()-]{7,32}$/.test(form.phone))next.phone='Enter a valid phone number.';const rating=Number(form.rating);if(form.rating&&(Number.isNaN(rating)||rating<0||rating>5))next.rating='Rating must be between 0 and 5.';setErrors(next);return !Object.keys(next).length}
 const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!validate())return;setSaving(true);setApiError('');try{onSaved(rider?await updateRider(rider.id,form):await createRider(form))}catch(error){if(error instanceof ApiError){const next:Errors={};Object.entries(error.fields).forEach(([field,messages])=>{if(field in empty)next[field as keyof RiderInput]=Array.isArray(messages)?messages.join(' '):String(messages)});setErrors(next)}setApiError('Unable to save this rider. Check the information and try again.')}finally{setSaving(false)}}
 return <div className="details-backdrop" role="presentation" onMouseDown={()=>!saving&&onClose()}><aside className="details-panel" role="dialog" aria-modal="true" aria-labelledby="rider-form-title" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">Rider management</p><h2 id="rider-form-title">{edit?'Edit rider':'Add rider'}</h2></div><IconButton label="Close rider form" onClick={onClose} disabled={saving}><X size={18}/></IconButton></header><form className="vendor-form" onSubmit={submit} noValidate>{apiError&&<div className="api-error">{apiError}</div>}<Field label="Full name" error={errors.full_name}><input value={form.full_name} onChange={e=>update('full_name',e.target.value)} autoFocus/></Field><Field label="Phone" error={errors.phone}><input type="tel" value={form.phone} onChange={e=>update('phone',e.target.value)}/></Field><Field label="Email" error={errors.email}><input type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></Field><Field label="Status" error={errors.status}><select value={form.status} onChange={e=>update('status',e.target.value as ApiRiderStatus)}><option value="available">Available</option><option value="on_delivery">On delivery</option><option value="offline">Offline</option></select></Field><Field label="Rating" error={errors.rating}><input type="number" min="0" max="5" step="0.1" value={form.rating} onChange={e=>update('rating',e.target.value)}/></Field><footer><Button type="button" onClick={onClose} disabled={saving}>Cancel</Button><Button type="submit" variant="primary" loading={saving}>{edit?'Save changes':'Add rider'}</Button></footer></form></aside></div>}
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="form-field"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
